name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-20.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libx11-dev libglu1-mesa-dev libpng-dev

      - uses: actions/checkout@v2

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build
